name: Release artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}
          cache-on-failure: true

      - name: Build
        run: |
          cargo build --locked --release --target "${{ matrix.target }}"

      - name: Export enviroment variables
        run: |
          echo "artifact_name=whiz-${{ github.ref_name }}-${{ matrix.target }}.zip" >> $GITHUB_ENV
          echo "build_name=whiz${{ matrix.suffix }}" >> $GITHUB_ENV
          echo "build_path=target/${{ matrix.target }}/release" >> $GITHUB_ENV

      - name: Zip
        run: |
          mv "${{ env.build_path }}/${{ env.build_name }}" .
          7z \
          a \
          -t7z \
          -mx=9 \
          -mfb=273 \
          -ms \
          -md=31 \
          -myx=9 \
          -mtm=- \
          -mmt \
          -mmtf \
          -md=1536m \
          -mmf=bt3 \
          -mmc=10000 \
          -mpb=0 \
          -mlc=0 \
          "${{ env.artifact_name }}" \
          "${{ env.build_name }}"

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "${{ env.artifact_name }}"
