name: Release artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}
          cache-on-failure: true

      - name: Build
        run: |
          cargo build --locked --release --target "${{ matrix.target }}"

      - name: Export enviroment variables
        run: |
          echo "build_name=whiz-${{ github.ref_name }}-${{ matrix.target }}" >> $GITHUB_ENV
          echo "build_path=target/${{ matrix.target }}/release" >> $GITHUB_ENV
          pwd
          ls

          echo "7z a ${{ env.build_name }}.zip ${{ env.build_path }}/whiz${{ matrix.suffix }}"

      - name: Debug
        run: |
          pwd
          ls
        working-directory: ${{ env.build_path }}

      - name: Zip
        run: |
          7z a "${{ env.build_name }}.zip" "${{ env.build_path }}/whiz${{ matrix.suffix }}"

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "${{ env.build_name }}.zip"
