use std::{
    fs,
    path::{Path, PathBuf},
};

use tempfile::TempDir;

/// A struct to save variables and output of the test.
pub struct TestSetup {
    /// Output generated by the command executed in the test.
    pub output: String,
    /// Test dir where the command was executed.
    pub test_dir: PathBuf,
}

/// Run the CLI with the given configurantion file returning its output and
/// the test directory.
pub fn run_config_file_test(config_path: &str) -> anyhow::Result<TestSetup> {
    let temp_test_dir = Path::new("test");

    fs::create_dir_all(temp_test_dir);

    // change the CLI base dir to the created temporal test dir
    let temp_config_path = temp_test_dir.join("whiz.yaml");
    fs::copy(config_path, &temp_config_path)?;

    let command = &format!("cargo run -- --file {}", temp_config_path.display());

    let mut process = rexpect::spawn(command, Some(5_000))?;
    let output = process.exp_string("Exited(0)")?;
    process.send_control('c')?;

    Ok(TestSetup {
        output,
        test_dir: temp_test_dir.to_path_buf(),
    })
}
